<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Sales\Block\Order\Email\Items\DefaultItems */

/** @var $_item \Magento\Sales\Model\Order\Item */
$_item = $block->getItem();
$_order = $_item->getOrder();
?>
<tr>
    <td class="item-info<?php if ($block->getItemOptions()): ?> has-extra<?php endif; ?>">
        <p class="product-name"><?= $block->escapeHtml($_item->getName()) ?></p>
        <p class="sku"><?= /* @escapeNotVerified */  __('SKU') ?>: <?= $block->escapeHtml($block->getSku($_item)) ?></p>
        <?php if ($block->getItemOptions()): ?>
            <dl class="item-options">
            <?php foreach ($block->getItemOptions() as $option): ?>
                <dt><strong><em><?= /* @escapeNotVerified */  $option['label'] ?></em></strong></dt>
                <dd>
                    <?= /* @escapeNotVerified */  nl2br($option['value']) ?>
                </dd>
            <?php endforeach; ?>
            </dl>
        <?php endif; ?>
        <?php
        $quote_item_id = $_item->getQuoteItemId();
        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        $resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
        $connection = $resource->getConnection();
        $magneto_quote = $resource->getTableName('magneto_quote');
        $sql = "Select * FROM " . $magneto_quote . " WHERE quote_item_id = " . $quote_item_id;
        $result_embroidery = $connection->fetchAll($sql);

        if($result_embroidery != ' '){ 
            $decode_data = array();
            foreach($result_embroidery as $embroidery){
                $jsonHelper = $objectManager->get('\Magento\Framework\Json\Helper\Data');
                $embroidery_decode = $jsonHelper->jsonDecode($embroidery['name_embroidery']);
                $decode_data = $embroidery_decode;
            }
            foreach ($decode_data as $value_emb) { ?>
                <dl class="embroidery-options item-options" style="text-transform: capitalize;">
                <dt><strong><?= $block->escapeHtml($value_emb['line']) ?></strong></dt>
                <dt><?= $block->escapeHtml(__('Font')) ?></dt>
                    <dd><?= $block->escapeHtml($value_emb['font']) ?></dd>
                <dt><?= $block->escapeHtml(__('Color')) ?></dt>
                    <dd><?= $block->escapeHtml($value_emb['color']) ?></dd>
                <dt><?= $block->escapeHtml(__('Placement')) ?></dt>
                    <dd><?= $block->escapeHtml($value_emb['placement']) ?></dd>
                <dt><?= $block->escapeHtml(__('Text')) ?></dt>
                    <dd><?= $block->escapeHtml($value_emb['name_text']) ?></dd>
                <dt><?= $block->escapeHtml(__('Comments')) ?></dt>
                    <dd><?= $block->escapeHtml($value_emb['comment']) ?></dd>
                </dl>
            <?php }
        } ?>
        <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock) :?>
            <?= $addInfoBlock->setItem($_item)->toHtml() ?>
        <?php endif; ?>
        <?= $block->escapeHtml($_item->getDescription()) ?>
    </td>
    <td class="item-qty"><?= /* @escapeNotVerified */  $_item->getQtyOrdered() * 1 ?></td>
    <td class="item-price">
        <?= /* @escapeNotVerified */  $block->getItemPrice($_item) ?>
    </td>
</tr>
<?php if ($_item->getGiftMessageId() && $_giftMessage = $this->helper('Magento\GiftMessage\Helper\Message')->getGiftMessage($_item->getGiftMessageId())): ?>
<tr>
    <td colspan="3" class="item-extra">
        <table class="message-gift">
            <tr>
                <td>
                    <h3><?= /* @escapeNotVerified */  __('Gift Message') ?></h3>
                    <strong><?= /* @escapeNotVerified */  __('From:') ?></strong> <?= $block->escapeHtml($_giftMessage->getSender()) ?>
                    <br /><strong><?= /* @escapeNotVerified */  __('To:') ?></strong> <?= $block->escapeHtml($_giftMessage->getRecipient()) ?>
                    <br /><strong><?= /* @escapeNotVerified */  __('Message:') ?></strong>
                    <br /><?= $block->escapeHtml($_giftMessage->getMessage()) ?>
                </td>
            </tr>
        </table>
    </td>
</tr>
<?php endif; ?>
