<?php
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $_helper = $this->helper('Magento\Catalog\Helper\Output');
    $_product = $block->getProduct();
    $_call = $block->getAtCall();
    $_code = $block->getAtCode();
    $_className = $block->getCssClass();
    $categoryCollection = $objectManager->get('\Magento\Catalog\Model\ResourceModel\Category\CollectionFactory');
    $buttonTitle = __('Add to Cart');
?>
<?php if ($_product->isSaleable()): ?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()): ?>
        <div class="field qty">
            <label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Qty') ?></span></label>
            <div class="control">
                <!-- <input type="number"
                       name="qty"
                       id="qty"
                       value="<?= /* @escapeNotVerified */ $block->getProductDefaultQty() * 1 ?>"
                       title="<?= /* @escapeNotVerified */ __('Quantity') ?>"
                       class="input-text qty"
                       data-validate="{required:true,'validate-greater-than-zero':true}"
                       /> -->
                <select class="input-text qty" name="qty" id="qty">
                    <?php $i = 1 ?>
                    <?php do { ?>
                        <option value="<?php echo $i?>">
                            <?php echo $i?>
                            <?php $i++ ?>
                        </option>
                    <?php } while ($i <= 10) ?>
                </select>
            </div>

            <!-- Embroidery Start -->
            <?php $is_embroidery =  $this->helper('Magento\Catalog\Helper\Output')->productAttribute($block->getProduct(), $block->getProduct()->getIsEmbroidery(), 'is_embroidery');
                if($is_embroidery == '1'):
            ?>
                    <script type="text/javascript">
                        require(['jquery'], function($){
                            $(document).ready(function(){
                                $('input[type=checkbox]').click(function(){
                                    var inputValue = $(this).attr("value");
                                    $("." + inputValue).toggle(); 
                                    if($('.red').is(':visible')){
                                        $("input").prop('required',true);
                                        
                                        // Enable/Disable Add to Cart On Click of Checkbox
                                        $("#agree_embroidery_check").click(function() {
                                            $("#product-addtocart-button").attr("disabled", !this.checked);
                                        });
                                    }

                                    // Enable Disable Add to Cart Button On click of checkbox
                                    $("#product-addtocart-button").attr("disabled", this.checked);
                                });
                            });
                        });
                    </script> 
                    <div class="embroidery_checkbox"><input type="checkbox" name="embroidery_checkbox" id="checkbox_emb" value="red"><span><?php echo $block->escapeHtml(__('Add embroidery to this item.')) ?></span></div>
                    
                <?php endif; ?>            
            <!-- Embroidery End -->
        </div>
        <?php endif; ?>

        <!-- Add to Cart Button     -->
        <div class="actions" id="add-action">
            <button type="submit" name="add_to_cart" title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>" class="action primary tocart" id="product-addtocart-button" value="add_to_cart">
                <?php /* @escapeNotVerified */ echo $buttonTitle ?>
            </button>
            <?php echo $block->getChildHtml('', true) ?>
        </div>      
    </div>
</div>

<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php if (!$block->isRedirectToCartEnabled()) : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "catalogAddToCart": {
                "bindSubmit": false
            }
        }
    }
</script>

<?php endif; ?>
