<div class="red embroidery_block" style="display: none;">
    <div class="blankembroidery"><?php echo $block->escapeHtml(__('Test Text')) ?></div>
    <div class="embroidery_options">
        <h2><?php echo $block->escapeHtml(__('Embroidery Options')) ?></h2>
        <div class="embroidery_options_start">
            <p><?php echo $block->escapeHtml(__('Please allow approximately 5 to 7 days to embroider your items.')) ?></p>
            <div class="embroidery_type">
                <div><input type="checkbox" name="name_embroidery" id="name_embroidery" value="name_start"><span><?php echo $block->escapeHtml(__('Name Embroidery')) ?></span></div>
                <div><input type="checkbox" name="stock_design" id="stock_design" value="stock_start"><span><?php echo $block->escapeHtml(__('Stock Design')) ?></span></div>
                <div><input type="checkbox" name="new_custom_logo" id="new_custom_logo" value="custom_logo_start"><span><?php echo $block->escapeHtml(__('New Custom Logo')) ?></span></div>
            </div>

            <div class="name_start" style="display: none;">
                <h3 class="embroideryheadingthree"><?php echo $block->escapeHtml(__('Name Embroidery - $5.99 Per Line')) ?></h3>
                <div class="lines_num">
                    <span><?php echo $block->escapeHtml(__('No. of lines')) ?></span>
                    <select name="options_3" id="options_3">
                        <option value="1"><?php echo $block->escapeHtml(__('1')) ?></option>
                        <option value="2"><?php echo $block->escapeHtml(__('2')) ?></option>
                        <option value="3"><?php echo $block->escapeHtml(__('3')) ?></option>
                    </select>
                </div>               

                <?php
                    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                    $colormodel = $objectManager->create('Magneto\Embroidery\Model\Color');
                    $colorCollection = $colormodel->getCollection();

                    $fontmodel = $objectManager->create('Magneto\Embroidery\Model\Font');
                    $fontCollection = $fontmodel->getCollection();
                ?>
                <div id="1" class="selectedoption one_1 1">
                    <div class="lines">
                        <?php echo $block->escapeHtml(__('Line 1')) ?>
                    </div>
                    <div class="font_style">
                        <h3><?php echo $block->escapeHtml(__('Font Style')) ?></h3>
                        <div class="font_grid">
                            <?php foreach ($fontCollection as $fonts) { ?>
                                <div class="fonts">                                        
                                    <div id="font_block fonts_<?php echo $fonts->getId() ?>" class="font_block fonts_<?php echo $fonts->getId() ?>" onclick="myFont (this, <?php echo $fonts->getId() ?>, '<?php echo $fonts->getFonts() ?>' )" style="font-family: <?php echo $fonts->getFontFamily() ?>">
                                        <?php echo $fonts->getFonts() ?>
                                    </div>
                                    <span class="font_name"><?php echo $fonts->getFonts() ?></span>
                                </div>                                
                            <?php } ?>                            
                        </div>
                    </div>
                    <div class="color_style">
                        <h3><?php echo $block->escapeHtml(__('Thread Color')) ?></h3>
                        <div class="color_grid" id="selectable_color">
                            <?php foreach ($colorCollection as $color) { ?>
                                <div class="color">                                        
                                    <div class="color_block color_<?php echo $color->getId() ?>" onclick="myColor (this, <?php echo $color->getId() ?>, '<?php echo $color->getThreadColor() ?>' )" style="background-color:#<?php echo $color->getColorCode() ?>;">
                                    </div>
                                    <span class="color_name"><?php echo $color->getThreadColor() ?></span>
                                </div>
                            <?php } ?>
                        </div>                                                   
                    </div>
                    <div class="placement_style">
                        <h3><?php echo $block->escapeHtml(__('Placement')) ?></h3>
                        <div class="placement_grid" id="selectable_placement">
                            <div class="chest left_chest" id="left_chest">
                                <img src='<?php echo $this->getViewFileUrl('images/lc.jpg'); ?>' alt="Left Chest" class="pimg left_chest_img" onclick='myPlacement (this, "left_chest_img", "left chest")'>
                                <div class="text_image"><?php echo $block->escapeHtml(__('Left Chest')) ?></div>
                            </div>
                            <div class="chest right_chest" id="right_chest">
                                <img src='<?php echo $this->getViewFileUrl('images/rc.jpg'); ?>' alt="Right Chest" class="pimg right_chest_img" onclick='myPlacement (this, "right_chest_img", "right chest")'>
                                <div class="text_image"><?php echo $block->escapeHtml(__('Right Chest')) ?></div>
                            </div>
                            <div class="chest left_sleeve" id="left_sleeve">
                                <img src='<?php echo $this->getViewFileUrl('images/ls.jpg'); ?>' alt="Left Sleeve" onclick='myPlacement (this, "left_sleeve_img", "left sleeve")' class="pimg left_sleeve_img">
                                <div class="text_image"><?php echo $block->escapeHtml(__('Left Sleeve')) ?></div>
                            </div>
                            <div class="chest right_sleeve" id="right_sleeve">
                                <img src='<?php echo $this->getViewFileUrl('images/rs.jpg'); ?>' alt="Right Sleeve" onclick='myPlacement (this, "right_sleeve_img", "right sleeve")' class="pimg right_sleeve_img">
                                <div class="text_image"><?php echo $block->escapeHtml(__('Right Sleeve')) ?></div>
                            </div>                            
                        </div>    
                    </div>
                    <div class="text_style">
                        <h3><?php echo $block->escapeHtml(__('Text')) ?></h3>
                        <span class="text_para_style"><?php echo $block->escapeHtml(__('Please enter text exactly as you would like it to appear. Maximum 25 Characters.')) ?></span>
                        <div class="text_style_input">
                            <div><input type="text" name="input_text_design" id="input_text_design" placeholder="Enter text here">
                        </div>
                            <textarea name="special_instructions" id="special_instructions" placeholder="Special instructions and/or comments"></textarea>
                        </div>
                    </div>                    
                </div>
                <div id="2" class="selectedoption two_2 2" style="display: none;">
                    <div class="line2">
                        <div class="lines">
                            <?php echo $block->escapeHtml(__('Line 2')) ?>
                        </div>
                        <div class="font_style">
                            <h3><?php echo $block->escapeHtml(__('Font Style')) ?></h3>
                            <div class="font_grid">
                                <?php foreach ($fontCollection as $fonts) { ?>
                                    <div class="fonts">                                        
                                        <div class="font_block2 fonts2_<?php echo $fonts->getId() ?>" onclick="myFont2 (this, <?php echo $fonts->getId() ?>, '<?php echo $fonts->getFonts() ?>' )" style="font-family: <?php echo $fonts->getFontFamily() ?>">
                                            <?php echo $fonts->getFonts() ?>
                                        </div>
                                        <span class="font_name"><?php echo $fonts->getFonts() ?></span>
                                    </div>                                
                                <?php } ?>                            
                            </div>
                        </div>
                        <div class="color_style">
                            <h3><?php echo $block->escapeHtml(__('Thread Color')) ?></h3>
                            <div class="color_grid" id="selectable_color">
                                <?php foreach ($colorCollection as $color) { ?>
                                    <div class="color">                                        
                                        <div class="color_block2 color2_<?php echo $color->getId() ?>" onclick="myColor2 (this, <?php echo $color->getId() ?>, '<?php echo $color->getThreadColor() ?>' )" style="background-color:#<?php echo $color->getColorCode() ?>;">
                                        </div>
                                        <span class="color_name"><?php echo $color->getThreadColor() ?></span>
                                    </div>
                                <?php } ?>
                            </div>                                                   
                        </div>
                        <div class="placement_style">
                        <h3><?php echo $block->escapeHtml(__('Placement')) ?></h3>
                        <div class="placement_grid" id="selectable_placement">
                            <div class="chest left_chest" id="left_chest">
                                <img src='<?php echo $this->getViewFileUrl('images/lc.jpg'); ?>' alt="Left Chest" class="pimg left_chest_img2" onclick='myPlacement2 (this, "left_chest_img2", "left chest")'>
                                <div class="text_image"><?php echo $block->escapeHtml(__('Left Chest')) ?></div>
                            </div>
                            <div class="chest right_chest" id="right_chest">
                                <img src='<?php echo $this->getViewFileUrl('images/rc.jpg'); ?>' alt="Right Chest" class="pimg right_chest_img2" onclick='myPlacement2 (this, "right_chest_img2", "right chest")'>
                                <div class="text_image"><?php echo $block->escapeHtml(__('Right Chest')) ?></div>
                            </div>
                            <div class="chest left_sleeve" id="left_sleeve">
                                <img src='<?php echo $this->getViewFileUrl('images/ls.jpg'); ?>' alt="Left Sleeve" onclick='myPlacement2 (this, "left_sleeve_img2", "left sleeve")' class="pimg left_sleeve_img2">
                                <div class="text_image"><?php echo $block->escapeHtml(__('Left Sleeve')) ?></div>
                            </div>
                            <div class="chest right_sleeve" id="right_sleeve">
                                <img src='<?php echo $this->getViewFileUrl('images/rs.jpg'); ?>' alt="Right Sleeve" onclick='myPlacement2 (this, "right_sleeve_img2", "right sleeve")' class="pimg right_sleeve_img2">
                                <div class="text_image"><?php echo $block->escapeHtml(__('Right Sleeve')) ?></div>
                            </div>                            
                        </div>    
                    </div>
                        <div class="text_style">
                            <h3><?php echo $block->escapeHtml(__('Text')) ?></h3>
                            <span class="text_para_style"><?php echo $block->escapeHtml(__('Please enter text exactly as you would like it to appear. Maximum 25 Characters.')) ?></span>
                            <div class="text_style_input">
                                <div><input type="text" name="input_text_design" id="input_text_design2" placeholder="Enter text here">
                            </div>
                                <textarea name="special_instructions" id="special_instructions2" placeholder="Special instructions and/or comments"></textarea>
                            </div>
                        </div>
                    </div>
                </div>
                <div id="3" class="selectedoption three_3 3" style="display: none;">
                    <div class="line3">
                        <div class="lines">
                            <?php echo $block->escapeHtml(__('Line 3')) ?>
                        </div>
                        <div class="font_style">
                            <h3><?php echo $block->escapeHtml(__('Font Style')) ?></h3>
                            <div class="font_grid">
                                <?php foreach ($fontCollection as $fonts) { ?>
                                    <div class="fonts">                                        
                                        <div class="font_block3 fonts3_<?php echo $fonts->getId() ?>" onclick="myFont3 (this, <?php echo $fonts->getId() ?>, '<?php echo $fonts->getFonts() ?>' )" style="font-family: <?php echo $fonts->getFontFamily() ?>">
                                            <?php echo $fonts->getFonts() ?>
                                        </div>
                                        <span class="font_name"><?php echo $fonts->getFonts() ?></span>
                                    </div>                                
                                <?php } ?>                            
                            </div>
                        </div>
                        <div class="color_style">
                            <h3><?php echo $block->escapeHtml(__('Thread Color')) ?></h3>
                            <div class="color_grid" id="selectable_color">
                                <?php foreach ($colorCollection as $color) { ?>
                                    <div class="color">                                        
                                        <div class="color_block3 color3_<?php echo $color->getId() ?>" onclick="myColor3 (this, <?php echo $color->getId() ?>, '<?php echo $color->getThreadColor() ?>' )" style="background-color:#<?php echo $color->getColorCode() ?>;">
                                        </div>
                                        <span class="color_name"><?php echo $color->getThreadColor() ?></span>
                                    </div>
                                <?php } ?>
                            </div>                                                   
                        </div>
                        <div class="placement_style">
                            <h3><?php echo $block->escapeHtml(__('Placement')) ?></h3>
                            <div class="placement_grid" id="selectable_placement">
                                <div class="chest left_chest" id="left_chest">
                                    <img src='<?php echo $this->getViewFileUrl('images/lc.jpg'); ?>' alt="Left Chest" class="pimg3 left_chest_img3" onclick='myPlacement3 (this, "left_chest_img3", "left chest")'>
                                    <div class="text_image"><?php echo $block->escapeHtml(__('Left Chest')) ?></div>
                                </div>
                                <div class="chest right_chest" id="right_chest">
                                    <img src='<?php echo $this->getViewFileUrl('images/rc.jpg'); ?>' alt="Right Chest" class="pimg3 right_chest_img3" onclick='myPlacement3 (this, "right_chest_img3", "right chest")'>
                                    <div class="text_image"><?php echo $block->escapeHtml(__('Right Chest')) ?></div>
                                </div>
                                <div class="chest left_sleeve" id="left_sleeve">
                                    <img src='<?php echo $this->getViewFileUrl('images/ls.jpg'); ?>' alt="Left Sleeve" onclick='myPlacement3 (this, "left_sleeve_img3", "left sleeve")' class="pimg left_sleeve_img3">
                                    <div class="text_image"><?php echo $block->escapeHtml(__('Left Sleeve')) ?></div>
                                </div>
                                <div class="chest right_sleeve" id="right_sleeve">
                                    <img src='<?php echo $this->getViewFileUrl('images/rs.jpg'); ?>' alt="Right Sleeve" onclick='myPlacement3 (this, "right_sleeve_img3", "right sleeve")' class="pimg right_sleeve_img3">
                                    <div class="text_image"><?php echo $block->escapeHtml(__('Right Sleeve')) ?></div>
                                </div>                            
                            </div>    
                        </div>
                        <div class="text_style">
                            <h3><?php echo $block->escapeHtml(__('Text')) ?></h3>
                            <span class="text_para_style"><?php echo $block->escapeHtml(__('Please enter text exactly as you would like it to appear. Maximum 25 Characters.')) ?></span>
                            <div class="text_style_input">
                                <div><input type="text" name="input_text_design" id="input_text_design3" placeholder="Enter text here">
                            </div>
                                <textarea name="special_instructions" id="special_instructions3" placeholder="Special instructions and/or comments"></textarea>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="stock_start" style="display: none;">
                <h3 class="embroideryheadingthree"><?php echo $block->escapeHtml(__('Stock Design - $8.99 Per Line')) ?></h3>
                <div class="lines_num">
                    <span><?php echo $block->escapeHtml(__('No. of logos')) ?></span>
                    <select name="options_2" id="options_2">
                        <option value="logo1"><?php echo $block->escapeHtml(__('1')) ?></option>
                        <option value="logo2"><?php echo $block->escapeHtml(__('2')) ?></option>
                    </select>
                </div>

                <div id="logo1" class="selectedoption logo_1">
                    <div class="lines">
                        <?php echo $block->escapeHtml(__('Stock Design 1')) ?>
                    </div>
                    <div class="stock_logo">
                        <?php
                        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                        $stockmodel = $objectManager->create('Magneto\Embroidery\Model\Stock');
                        $stockCollection = $stockmodel->getCollection();

                        $storeManager = $objectManager->get('Magento\Store\Model\StoreManagerInterface'); 
                        $currentStore = $storeManager->getStore();
                        $mediaUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);

                        foreach ($stockCollection as $stockData) {
                            if($stockData['stock_design'] != ' '):
                            ?>

                            <div class="logoname logoname_<?php echo $stockData['id'] ?>" onclick="stockimg(this,<?php echo $stockData['id'] ?>,'<?php echo $stockData['stock_design_name'] ?>')">
                                <img src='<?php echo $mediaUrl.'embroidery/'.$stockData['stock_design'] ?>' alt="Stock Design">
                            </div>
                            <?php
                            endif;
                        }
                        ?>
                    </div>
                    <div class="stock_placement">
                        <h3><?php echo $block->escapeHtml(__('Placement')) ?></h3>
                        <div class="placement_grid" id="selectable_placement">
                            <div class="chest stock_left_chest" id="stock_left_chest">
                                <img src='<?php echo $this->getViewFileUrl('images/lc.jpg'); ?>' alt="Left Chest" class="pimg stock_left_chest_img" onclick='StockPlacement(this, "stock_left_chest_img", "left chest")'>
                                <div class="text_image"><?php echo $block->escapeHtml(__('Left Chest')) ?></div>
                            </div>
                            <div class="chest stock_right_chest" id="stock_right_chest">
                                <img src='<?php echo $this->getViewFileUrl('images/rc.jpg'); ?>' alt="Right Chest" class="pimg stock_right_chest_img" onclick='StockPlacement (this, "stock_right_chest_img", "right chest")'>
                                <div class="text_image"><?php echo $block->escapeHtml(__('Right Chest')) ?></div>
                            </div>
                            <div class="chest stock_left_sleeve" id="stock_left_sleeve">
                                <img src='<?php echo $this->getViewFileUrl('images/ls.jpg'); ?>' alt="Left Sleeve" onclick='StockPlacement (this, "stock_left_sleeve_img", "left sleeve")' class="pimg stock_left_sleeve_img">
                                <div class="text_image"><?php echo $block->escapeHtml(__('Left Sleeve')) ?></div>
                            </div>
                            <div class="chest stock_right_sleeve" id="stock_right_sleeve">
                                <img src='<?php echo $this->getViewFileUrl('images/rs.jpg'); ?>' alt="Right Sleeve" onclick='StockPlacement (this, "stock_right_sleeve_img", "right sleeve")' class="pimg stock_right_sleeve_img">
                                <div class="text_image"><?php echo $block->escapeHtml(__('Right Sleeve')) ?></div>
                            </div>                            
                        </div>    
                    </div>
                    <div class="stock_position">
                        <h3><?php echo $block->escapeHtml(__('Positioning')) ?></h3>
                        <div class="position_select" id="selectable_position">
                            <div class="position">                                        
                                <div class="above_text" onclick="positionVal(this, 'above_text', 'above text')"><?= $block->escapeHtml(__('Above Text')) ?></div>
                                <div class="below_text" onclick="positionVal(this, 'below_text', 'below text')"><?= $block->escapeHtml(__('Below Text')) ?></div>
                                <div class="left_text" onclick="positionVal(this, 'left_text', 'left of text')"><?= $block->escapeHtml(__('Left of Text')) ?></div>
                                <div class="right_text" onclick="positionVal(this, 'right_text','right of text')"><?= $block->escapeHtml(__('Right of Text')) ?></div>
                                <div class="through_logo" onclick="positionVal(this, 'through_logo','through logo')"><?= $block->escapeHtml(__('Through Logo')) ?></div>
                            </div>
                        </div>
                    </div>
                    <div class="stock_comments">
                        <textarea name="textarea_stock_comments" id="stock_comments" placeholder="Special instructions and/or comments"></textarea>
                    </div>
                </div> 

                <div id="logo2" class="selectedoption logo_2">
                    <div class="lines">
                        <?php echo $block->escapeHtml(__('Stock Design 2')) ?>
                    </div>
                    <div class="stock_logo">
                        <?php
                        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                        $stockmodel = $objectManager->create('Magneto\Embroidery\Model\Stock');
                        $stockCollection = $stockmodel->getCollection();

                        $storeManager = $objectManager->get('Magento\Store\Model\StoreManagerInterface'); 
                        $currentStore = $storeManager->getStore();
                        $mediaUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);

                        foreach ($stockCollection as $stockData) {
                            if($stockData['stock_design'] != ' '):
                            ?>

                            <div class="logoname logoname2_<?php echo $stockData['id'] ?>" onclick="stockimg2(this, <?php echo $stockData['id'] ?>,'<?php echo $stockData['stock_design_name'] ?>')">
                                <img src='<?php echo $mediaUrl.'embroidery/'.$stockData['stock_design'] ?>' alt="Stock Design">
                            </div>
                            <?php
                            endif;
                        }
                        ?>
                    </div>
                    <div class="stock_placement">
                        <h3><?php echo $block->escapeHtml(__('Placement')) ?></h3>
                        <div class="placement_grid" id="selectable_placement">
                            <div class="chest stock_left_chest" id="stock_left_chest">
                                <img src='<?php echo $this->getViewFileUrl('images/lc.jpg'); ?>' alt="Left Chest" class="pimg stock_left_chest_img" onclick='StockPlacement2(this, "stock_left_chest_img", "left chest")'>
                                <div class="text_image"><?php echo $block->escapeHtml(__('Left Chest')) ?></div>
                            </div>
                            <div class="chest stock_right_chest" id="stock_right_chest">
                                <img src='<?php echo $this->getViewFileUrl('images/rc.jpg'); ?>' alt="Right Chest" class="pimg stock_right_chest_img" onclick='StockPlacement2(this, "stock_right_chest_img", "right chest")'>
                                <div class="text_image"><?php echo $block->escapeHtml(__('Right Chest')) ?></div>
                            </div>
                            <div class="chest stock_left_sleeve" id="stock_left_sleeve">
                                <img src='<?php echo $this->getViewFileUrl('images/ls.jpg'); ?>' alt="Left Sleeve" onclick='StockPlacement2(this, "stock_left_sleeve_img", "left sleeve")' class="pimg stock_left_sleeve_img">
                                <div class="text_image"><?php echo $block->escapeHtml(__('Left Sleeve')) ?></div>
                            </div>
                            <div class="chest stock_right_sleeve" id="stock_right_sleeve">
                                <img src='<?php echo $this->getViewFileUrl('images/rs.jpg'); ?>' alt="Right Sleeve" onclick='StockPlacement2(this, "stock_right_sleeve_img", "right sleeve")' class="pimg stock_right_sleeve_img">
                                <div class="text_image"><?php echo $block->escapeHtml(__('Right Sleeve')) ?></div>
                            </div>                            
                        </div>    
                    </div>
                    <div class="stock_position">
                        <h3><?php echo $block->escapeHtml(__('Positioning')) ?></h3>
                        <div class="position_select" id="selectable_position">
                            <div class="position">                                        
                                <div class="above_text" onclick="positionVal2(this, 'above_text', 'above text')"><?= $block->escapeHtml(__('Above Text')) ?></div>
                                <div class="below_text" onclick="positionVal2(this, 'below_text', 'below text')"><?= $block->escapeHtml(__('Below Text')) ?></div>
                                <div class="left_text" onclick="positionVal2(this, 'left_text', 'left of text')"><?= $block->escapeHtml(__('Left of Text')) ?></div>
                                <div class="right_text" onclick="positionVal2(this, 'right_text','right of text')"><?= $block->escapeHtml(__('Right of Text')) ?></div>
                                <div class="through_logo" onclick="positionVal2(this, 'through_logo','through logo')"><?= $block->escapeHtml(__('Through Logo')) ?></div>
                            </div>
                        </div>
                    </div>
                    <div class="stock_comments">
                        <textarea name="textarea_stock_comments" id="stock_comments2" placeholder="Special instructions and/or comments"></textarea>
                    </div>
                </div>  

            </div>
            <!-- <div class="custom_logo_start" style="display: none;">
                Custom Logo Design Here
            </div> -->
        </div>
    </div>
    
    
    <div class="embroidery_summary">
        <div id="stickydiv"></div>
        <div class="embr_border">
            <h2><?php echo $block->escapeHtml(__('Embroidery Summary')) ?></h2>
            <div class="summary_attributes">  
                <div class="name_design_cus" id="cus_name" style="display: none;">
                    <div class="forline1 selectedoption 1" id="1">
                        <div class="line1 summarys">
                            <div class="line_summary_heading">
                                <h2 class="line_value" id="line_value1"><?php echo $block->escapeHtml(__('Line 1: ')) ?></h2>
                            </div>
                            <div class="heading_summary">
                                <h4><?php echo $block->escapeHtml(__('Font Style')) ?></h4>
                                <div class="font_value"></div>
                            </div>
                            <div class="heading_summary">
                                <h4><?php echo $block->escapeHtml(__('Thread Color')) ?></h4>
                                <div class="thread_color_value"></div>
                            </div>
                            <div class="heading_summary">
                                <h4><?php echo $block->escapeHtml(__('Placement')) ?></h4>
                                <div class="placement_value"></div>
                            </div>
                            <input type="hidden" name="name_value" id="name_value" value=""/>
                        </div>                    
                    </div>
                    <div class="forline2 selectedoption 2" id="2" style="display: none;">
                        <div class="line2 summarys">
                            <div class="line_summary_heading">
                                <h2 class="line_value" id="line_value2"><?php echo $block->escapeHtml(__('Line 2: ')) ?></h2>
                            </div>
                            <div class="heading_summary">
                                <h4><?php echo $block->escapeHtml(__('Font Style')) ?></h4>
                                <div class="font_value2"></div>
                            </div>
                            <div class="heading_summary">
                                <h4><?php echo $block->escapeHtml(__('Thread Color')) ?></h4>
                                <div class="thread_color_value2"></div>
                            </div>
                            <div class="heading_summary">
                                <h4><?php echo $block->escapeHtml(__('Placement')) ?></h4>
                                <div class="placement_value2"></div>
                            </div>
                            <input type="hidden" name="name_value2" id="name_value2" value=""/>
                        </div>                        
                    </div>
                    <div class="forline3 selectedoption 3" id="3" style="display: none;">
                        <div class="line3 summarys">
                            <div class="line_summary_heading">
                                <h2 class="line_value" id="line_value3"><?php echo $block->escapeHtml(__('Line 3: ')) ?></h2>
                            </div>
                            <div class="heading_summary">
                                <h4><?php echo $block->escapeHtml(__('Font Style')) ?></h4>
                                <div class="font_value3"></div>
                            </div>
                            <div class="heading_summary">
                                <h4><?php echo $block->escapeHtml(__('Thread Color')) ?></h4>
                                <div class="thread_color_value3"></div>
                            </div>
                            <div class="heading_summary">
                                <h4><?php echo $block->escapeHtml(__('Placement')) ?></h4>
                                <div class="placement_value3"></div>
                            </div>
                            <input type="hidden" name="name_value3" id="name_value3" value=""/>
                        </div>
                    </div>
                </div>
                <div class="stock design" id="cus_stock" style="display: none;">
                    <div class="stock_logo1">
                        <div class="heading_summary">
                            <h2 class="logo_value" id="logo_value1"><?php echo $block->escapeHtml(__('Logo 1 ')) ?></h2>
                        </div>                        
                        <div class="heading_summary">
                                <h4><?php echo $block->escapeHtml(__('Stock Design')) ?></h4>
                                <div class="stock_value"></div>
                            </div>
                        <div class="heading_summary">
                            <h4><?php echo $block->escapeHtml(__('Placement')) ?></h4>
                            <div class="stockplacement_value"></div>
                        </div>
                        <div class="heading_summary">
                            <h4><?php echo $block->escapeHtml(__('Positioning')) ?></h4>
                            <div class="stockpositionalue"></div>
                        </div>
                    </div>
                    <div class="stock_logo2">
                        <div class="heading_summary">
                            <h2 class="logo_value" id="logo_value2"><?php echo $block->escapeHtml(__('Logo 2 ')) ?></h2>
                        </div>                        
                        <div class="heading_summary">
                                <h4><?php echo $block->escapeHtml(__('Stock Design')) ?></h4>
                                <div class="stock_value2"></div>
                            </div>
                        <div class="heading_summary">
                            <h4><?php echo $block->escapeHtml(__('Placement')) ?></h4>
                            <div class="stockplacement_value2"></div>
                        </div>
                        <div class="heading_summary">
                            <h4><?php echo $block->escapeHtml(__('Positioning')) ?></h4>
                            <div class="stockpositionalue2"></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="embroidery_agree">
                <p><?php echo $block->escapeHtml(__('Please be sure your embroidery and placement shown above are correct as embroidered items cannot be exchanged or returned. If correct please click the box below and then click "Add to Cart" to continue')) ?></p>
                <div class="agree_check"><input type="checkbox" name="agree_embroidery_check" id="agree_embroidery_check"><span><?php echo $block->escapeHtml(__('Embroidery and placement above are correct.')) ?></span>
                </div>
            </div>         
        </div>        
    </div>        
</div>

<script type="text/javascript">
require(['jquery'], function($){
    // Dropdown Options Visibility
    $('#options_3').change(function(){
        if($(this).val() == '1'){
            $('.1').css('display','block');
            $('.2').css('display','none');
            $('.3').css('display','none');
        }
        if($(this).val() == '2'){
            $('.1').css('display','block');
            $('.2').css('display','block');
            $('.3').css('display','none');
        }
        if($(this).val() == '3'){
            $('.1').css('display','block');
            $('.2').css('display','block');
            $('.3').css('display','block');
        }
    }); 

    $('#options_2').change(function(){
        if($(this).val() == '1'){
            $('.logo1').css('display','block');
            $('.logo2').css('display','none');
        }
        if($(this).val() == '2'){
            $('.logo1').css('display','block');
            $('.logo2').css('display','block');
        }
    }); 

    // Ajax Call & Comment Function On Click of Add to Cart
    $('#product-addtocart-button').click(function(){
        // For Name Embroidery
        // Comments Textbox
        var comment_val = $('#special_instructions').val();                
        var comment_val2 = $('#special_instructions2').val();
        var comment_val3 = $('#special_instructions3').val();
        // Name Text
        var text_val = $('#input_text_design').val();
        $('#name_value').val(text_val);
        var text_val2 = $('#input_text_design2').val();
        $('#name_value2').val(text_val2);
        var text_val3 = $('#input_text_design3').val();
        $('#name_value3').val(text_val3);

        // Fonts for Line 1 , Line 2, Line 3
        var font = $('.font_value').text();
        var font2 = $('.font_value2').text();
        var font3 = $('.font_value3').text();
        // Color for Line 1 , Line 2, Line 3
        var color_value = $('.thread_color_value').text();
        var color_value2 = $('.thread_color_value2').text();
        var color_value3 = $('.thread_color_value3').text();
        // Placement for Line 1 , Line 2, Line 3
        var placement_value = $('.placement_value').text();
        var placement_value2 = $('.placement_value2').text();
        var placement_value3 = $('.placement_value3').text();
        // Input Text for Line 1 , Line 2, Line 3
        var input_valsname = $('#name_value').val();
        var input_valsname2 = $('#name_value2').val();
        var input_valsname3 = $('#name_value3').val();

        // For Stock Design
        // Logo 1
        var stock_comment = $('#stock_comments').val();
        var logo_value = $('#logo_value1').text();
        var stock_value = $('.stock_value').text();
        var stockplacement_value = $('.stockplacement_value').text();
        var position_value = $('.stockpositionalue').text();

        // Logo 2
        var stock_comment2 = $('#stock_comments2').val();
        var logo_value2 = $('#logo_value2').text();
        var stock_value2 = $('.stock_value2').text();
        var stockplacement_value2 = $('.stockplacement_value2').text();
        var position_value2 = $('.stockpositionalue2').text();

        var url = "<?php echo $block->getBaseUrl().'embroidery/index/embroidery/' ?>";
        jQuery.ajax({
            url: url,
            type: "POST",
            data: {textatra_value_comment:comment_val, font:font, color_value:color_value, placement_value:placement_value,input_valsname:input_valsname, textatra_value_comment2:comment_val2, font2:font2, color_value2:color_value2, placement_value2:placement_value2,input_valsname2:input_valsname2, textatra_value_comment3:comment_val3, font3:font3, color_value3:color_value3, placement_value3:placement_value3,input_valsname3:input_valsname3, stock_comment: stock_comment, logo_value: logo_value, stock_value:stock_value, stockplacement_value: stockplacement_value, position_value: position_value, logo_value2: logo_value2, stock_value2:stock_value2, stockplacement_value2: stockplacement_value2, position_value2: position_value2},
            success: function(response){
                // console.log(response);
            }
        });
    });     

    $('#stock_design').change(function() {
        $('#cus_stock').toggle();
    });  
    $('#name_embroidery').change(function() {
        $('#cus_name').toggle();
    });          
});
// Onclick Font 1
function myFont(obj,id,font_name){
    require(['jquery'], function($){
        $('.font_block.selected_font').removeClass('selected_font');
        $('.fonts_'+id).addClass('selected_font');
        $('.font_value').html(' ');
        $('.font_value').append(font_name);
        $(this).prop('required',true);
    });
}
// Onclick Font 2
function myFont2(obj,id,font_name){
    require(['jquery'], function($){
        $('.font_block2.selected_font').removeClass('selected_font');
        $('.fonts2_'+id).addClass('selected_font');
        $('.font_value2').html(' ');
        $('.font_value2').append(font_name);
        $(this).prop('required',true);
    });
}
// Onclick Font 1
function myFont3(obj,id,font_name){
    require(['jquery'], function($){
        $('.font_block3.selected_font').removeClass('selected_font');
        $('.fonts3_'+id).addClass('selected_font');
        $('.font_value3').html(' ');
        $('.font_value3').append(font_name);
        $(this).prop('required',true);
    });
}
// Onclick Color 1
function myColor(obj,id, color_name){
    require(['jquery'], function($){
        $('.color_block.selected_color').removeClass('selected_color');
        $('.color_'+id).addClass('selected_color');
        $('.thread_color_value').html(' ');
        $('.thread_color_value').append(color_name);
        $(this).prop('required',true);
    });
}
// Onclick Color 2
function myColor2(obj,id, color_name){
    require(['jquery'], function($){
        $('.color_block2.selected_color').removeClass('selected_color');
        $('.color2_'+id).addClass('selected_color');
        $('.thread_color_value2').html(' ');
        $('.thread_color_value2').append(color_name);
        $(this).prop('required',true);
    });
}
// Onclick Color 3
function myColor3(obj,id, color_name){
    require(['jquery'], function($){
        $('.color_block3.selected_color').removeClass('selected_color');
        $('.color3_'+id).addClass('selected_color');
        $('.thread_color_value3').html(' ');
        $('.thread_color_value3').append(color_name);
        $(this).prop('required',true);
    });
}
// Onclick Placement 1
function myPlacement(obj,text, value){
    require(['jquery'], function($){
        $('.selected_placement').removeClass('selected_placement');
        $('.'+text).addClass('selected_placement');
        $('.placement_value').html(' ');
        $('.placement_value').append(value);
        $(this).prop('required',true);
    });
}
// Onclick Placement 2
function myPlacement2(obj,text, value){
    require(['jquery'], function($){
        $('.selected_placement').removeClass('selected_placement');
        $('.'+text).addClass('selected_placement');
        $('.placement_value2').html(' ');
        $('.placement_value2').append(value);
        $(this).prop('required',true);
    });
}
// Onclick Placement 3
function myPlacement3(obj,text, value){
    require(['jquery'], function($){
        $('.selected_placement').removeClass('selected_placement');
        $('.'+text).addClass('selected_placement');
        $('.placement_value3').html(' ');
        $('.placement_value3').append(value);
        $(this).prop('required',true);
    });
}
function sticky_relocate() {
    require(['jquery'], function($){
        var window_top = $(window).scrollTop();
        var div_top = $('#stickydiv').offset().top;
        if (window_top > div_top ) {
            $('#add-action').addClass('sticky');
            $('.embr_border').addClass('sticky');
        } else {
            $('#add-action').removeClass('sticky');
            $('.embr_border').removeClass('sticky');
        }
    });
}
require(['jquery'], function($){
$(function() {
  $(window).scroll(sticky_relocate);
  sticky_relocate();
});
});

function stockimg (obj,id,name) {
    require(['jquery'], function($){
        $('.logoname.selected_logo').removeClass('selected_logo');
        $('.logoname_'+id).addClass('selected_logo');
        $('.stock_value').html(' ');
        $('.stock_value').append(name);
        $(this).prop('required',true);
    });
}
function stockimg2(obj,id,name) {
    require(['jquery'], function($){
        $('.selected_logo').removeClass('selected_logo');
        $('.logoname2_'+id).addClass('selected_logo');
        $('.stock_value2').html(' ');
        $('.stock_value2').append(name);
        $(this).prop('required',true);
    });
}
function StockPlacement(obj,text, value){
    require(['jquery'], function($){
        $('.selected_stock').removeClass('selected_stock');
        $('.'+text).addClass('selected_stock');
        $('.stockplacement_value').html(' ');
        $('.stockplacement_value').append(value);
        $(this).prop('required',true);
    });
}
function StockPlacement2(obj,text, value){
    require(['jquery'], function($){
        $('.selected_stock').removeClass('selected_stock');
        $('.'+text).addClass('selected_stock');
        $('.stockplacement_value2').html(' ');
        $('.stockplacement_value2').append(value);
        $(this).prop('required',true);
    });
}
function positionVal(obj, text, value){
    require(['jquery'], function($){
        $('.selected_position').removeClass('selected_position');
        $('.'+text).addClass('selected_position');
        $('.stockpositionalue').html(' ');
        $('.stockpositionalue').append(value);
        $(this).prop('required',true);
    });
}
function positionVal2(obj, text, value){
    require(['jquery'], function($){
        $('.selected_position').removeClass('selected_position');
        $('.'+text).addClass('selected_position');
        $('.stockpositionalue2').html(' ');
        $('.stockpositionalue2').append(value);
        $(this).prop('required',true);
    });
}
</script>
<style type="text/css">
    .embr_border.sticky {
        position: fixed;
        top: 60px;
        right: 0;
        margin-right: 17em;
        background-color: #fff;
        z-index: 99;
        width: 30%;
    }
    .actions.sticky {
        position: fixed;
        top: 10px;
        right: 0;
        margin-right: 13.5em;
        background-color: #fff;
        z-index: 99;
        width: 34%;
    }
</style>                                    