<fieldset class="fieldset create account" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
    <div class="field mobile_number">
        <label for="mobile_number" class="label"><span><?php /* @escapeNotVerified */ echo __('Mobile Number') ?></span></label>
        <div class="control">
            <input type="text" name="mobile_number" id="mobile_number" title="<?php /* @escapeNotVerified */ echo __('Mobile Number') ?>" class="input-text" data-validate="{required:false}" autocomplete="off">
        </div>
    </div>
    <div class="field loyalty_check">
        <label for="loyalty_check" class="label"><span><?php /* @escapeNotVerified */ echo __('Loyalty Check') ?></span></label>
        <div class="control">
            <input type="text" name="loyalty_check" id="loyalty_check" title="<?php /* @escapeNotVerified */ echo __('Loyalty Check') ?>" class="input-text" data-validate="{required:false}" autocomplete="off">
        </div>
    </div>
</fieldset>